services:
  eurobot-2025-web:
    build:
      context: .
      dockerfile: Dockerfile
    image: scx/eurobot-2025-web:latest
    container_name: eurobot-2025-web
    # ports:
    #   - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - /home/share/data:/home/share/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    network_mode: "host"
