services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: scx/eurobot-2025-web:dev
    ports:
      # - "3000:3000"
      - "5173:5173" # Vite dev server
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./:/app
      - /app/node_modules
    command: bun run dev -- --host 0.0.0.0
