services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: scx/eurobot-2025-web:dev
    # ports:
    #   - "3000:3000"   # React app
    #   - "3001:3001"   # API server
    #   - "5173:5173"   # Vite dev server
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
      - API_SERVER_PORT=3001
    volumes:
      - ./:/app
      - /app/node_modules
      # - /home/share/data:/home/share/data
    command: sh -c "bun install && node src/server.js & bun run dev -- --host 0.0.0.0"
    network_mode: "host"
